### ISSUE TITLE
How to implement the server

### ISSUE THREAD

**Issue by artemyarulin** [badsyntax/grpc-js-types#1]
Thank you very much for your example, but I'm not sure how to implement the actual logic and a server?

I guess it should look something like that, but I struggle how to actually implement the interface? 
```ts 
// src/index.ts
import * as grpc from '@grpc/grpc-js'
import * as services from './proto/echo_service_grpc_pb'

class EchoService implements services.IEchoServiceService {
    // ?
}

var server = new grpc.Server();
server.addService(services.EchoServiceService, new EchoService());
server.bindAsync("127.0.0.1:50051", grpc.ServerCredentials.createInsecure(), (err, port) => {
    if (!err) server.start();
});
```

Or is there is something missing? For example in https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/b7b5e97349d3f9463214f4cc65e2ec2c9e44320a/examples/src/grpcjs/proto/book_grpc_pb.d.ts#L57-L62 there is also additional interface `IBookServiceServer`  defined which I guess should be used as implementation interface for servers but here it's missing?

**Comment by badsyntax** [comment]
I'll add an example to this repo. Will update this issue when I've done so.

**Comment by artemyarulin** [comment]
Figured out, had two issues - server interface was indeed missing, in my project that was a solution https://github.com/agreatfool/grpc_tools_node_protoc_ts/issues/38#issuecomment-616870865

Then implementing interface is straightforward with one exception that `server.addService` expects service as a first parameter but in TypeScript it's defined as `export const APIService: IAPIService;` and evaluated to undefined in runtime. So fix is importing it from JS file, took it from here https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/src/grpcjs/server.ts#L75-L76

Full example
```ts
import * as grpc from "@grpc/grpc-js";
import {sendUnaryData} from "@grpc/grpc-js/build/src/server-call";
import {TestReq, TestResp} from "./proto/schema_pb";
import {IAPIServer} from "./proto/schema_grpc_pb";
import * as schemaGRPC from "./proto/schema_grpc_pb"

class API implements IAPIServer {
    public test(call: grpc.ServerUnaryCall<TestReq, TestResp>, callback: sendUnaryData<TestResp>) {
        const book = new TestResp();
        callback(null, book);
    }
}

function startServer() {
    const server = new grpc.Server();
    // HACK: Service definition is missing in TypeScript file and has to be exported from JS file
    // @ts-ignore
    server.addService(schemaGRPC['schema.API'], new API());
    server.bindAsync("127.0.0.1:50051", grpc.ServerCredentials.createInsecure(), (err, port) => {
        if (err) {
            throw err;
        }
        console.log(`Server started, listening: 127.0.0.1:${port}`);
        server.start();
    });
}
startServer();
```

**Comment by badsyntax** [comment]
There's a couple things to note here:

- originally this repo was demonstrating using https://github.com/improbable-eng/ts-protoc-gen which does not provide types for the server implementation
- https://github.com/agreatfool/grpc_tools_node_protoc_ts does provide server types, but it's not ideal, as you've discovered, as you need to use `// @ts-ignore` or not use a class to implement the interface (you can use a plain object eg `const ServerImpl: IBookServiceServer`) to avoid the type error)

I am attempting to improve the typings here but it requires changes from grpc upstream. See https://github.com/grpc/grpc-node/pull/1590, https://github.com/grpc/grpc-node/pull/1587, https://github.com/grpc/grpc-node/pull/1474#discussion_r500487961

Once the types have improved in upstream, i will update both https://github.com/improbable-eng/ts-protoc-gen and https://github.com/agreatfool/grpc_tools_node_protoc_ts as well as the examples in this repo.

**Comment by badsyntax** [comment]
I've added a PR to add server types to `ts-protoc-gen`: https://github.com/improbable-eng/ts-protoc-gen/pull/247

I'd recommend checking out the soon-to-be-released proto-loader typescript generator: https://github.com/badsyntax/grpc-js-types/tree/master/examples/grpc-proto-loader

**Comment by badsyntax** [comment]
All 3 tools now generate a server interface! Hopefully this will make life for people. I've updated the examples in this repo. Am closing now.
